services:
    php-fpm:
        container_name: php-fpm
        build:
            context: ./docker
            dockerfile: Dockerfile
        environment:
            PHP_IDE_CONFIG: "serverName=test"
        volumes:
            - ./:/var/www
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - App-network
        depends_on:
            - db
            - redis
        restart: always

    nginx:
        container_name: http-server
        image: nginx
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - '8080:80'
        networks:
            - App-network
        restart: always
        depends_on:
            - php-fpm

    db:
        container_name: db-mysql
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './storage/mysql:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - App-network
        restart: always

    redis:
        container_name: db-redis
        image: redis:alpine
        ports:
            - '6379:6379'
        command: [ "redis-server", "--appendonly", "yes" ]
        volumes:
            - './storage/redis:/data'
        restart: always
        networks:
            - App-network

networks:
    App-network:
        driver: bridge
